version: '3'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
    - 'postgres:/var/lib/postgresql/data'
    env_file:
    - '.env'
    ports:
    - '6543:5432'
  repartelo:
    depends_on:
    - 'postgres'
    # - 'webpacker'
    build: .
    ports:
    - '4000:3000'
    volumes:
    - '.:/app'
    env_file:
    - '.env'
  # webpacker:
  #   build: .
  #   command: ruby bin/webpack-dev-server
  #   volumes:
  #   - .:/app
  #   ports:
  #   - "4035:3035"
  # chrome:
  #   image: selenium/node-chrome:3.14
  #   depends_on:
  #   - hub
  #   environment:
  #     HUB_HOST: hub
  # firefox:
  #   image: selenium/node-firefox
  #   depends_on:
  #   - hub
  #   environment:
  #     HUB_HOST: hub
  # hub:
  #   image: selenium/hub
  #   ports:
  #   - "4444:4444"

volumes:
  postgres:
