# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: repartelo2_0_development
  username: postgres
  password: k4m4l30n
  host: localhost

test:
  <<: *development
  database: repartelo2_0_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

acceptance_test:
  <<: *default
  password: k4m4l30n
  database: dockerized_app
  username: postgres
  host: localhost
  port: 6543

